/* ================================================================
   CoverThumbnail — 封面缩略图（静态单帧）

   布局：背景为 AI 生成的插画，上方叠加标题文字
   用于生成视频封面/缩略图，风格与视频一致

   ─────────────────────────────────────────────────────────────
   视觉调定参数 (Tuned 2026-06-05)
   ─────────────────────────────────────────────────────────────
   字号按 1920×1080 参考分辨率锁定（运行时 d.scaled() 缩放）：

     主标题 (title)        96 px  →  三段式排比单行
     日期 (dateLabel)      76 px  →  标题的 0.79 倍
     品牌条 (brand)        70 px  →  标题的 0.73 倍

   字号比例 1.0 : 0.79 : 0.73（黄金三段层级），已通过 B 站/YouTube
   缩略图 320×180 下可读性验证。**不要轻易改这些数字**。

   规则：
   - 仅渲染 3 个元素：日期 / 主标题 / 品牌条，从上到下 flex column
   - 不用副标题（缩略图下不可读，已删除）
   - 不用 emoji、不用「【】!?」
   - 渐变遮罩 `linear-gradient(to bottom, rgba(0,0,0,0.1) 0%, rgba(0,0,0,0.2) 50%, rgba(0,0,0,0.75) 100%)`

   标题格式由 `prompts/title.md` 控制：
   - 三段式排比（"X写代码、Y挖漏洞、Z关起来"）
   - 单条主推标题放 `title` 字段
   - 中文 12-25 字
   ================================================================ */

import React from "react";
import { Img, staticFile } from "remotion";
import { useDesign, FONTS, FW, COLORS } from "./design";

/** 封面字号（@1920×1080 参考）— 调定后不要改 */
const COVER_FS = {
  title: 132,
  titleSmall: 112,
  kicker: 70,
  dateLabel: 82,
  tag: 42,
  brand: 30,
  logo: 64,
  logoText: 36,
  brandBarWidth: 5,
  brandBarHeight: 26,
  // 2026-06-06: 底部留白 20% (216px @ 1080p) 给 B 站 overlay (播放/时长/弹幕角标)
  // 之前 80px 太贴底, 模板里写 300px 太保守, 改 216
  contentBottom: 216,
  contentLeft: 280,
  contentRight: 280,
  contentGap: 20,
  tagGap: 24,
  tagPaddingX: 16,
  tagPaddingY: 9,
  brandGap: 28,
  brandMarginTop: 12,
} as const;

/** 品牌条文案 */
const BRAND_TEXT = "HNTechPulse";

export interface CoverThumbnailProps {
  /** 背景插画路径（相对于 public/） */
  backgroundImage: string;
  /** 主标题 */
  title: string;
  /** 副标题（可选 — 当前版本不渲染） */
  subtitle?: string;
  /** Supporting topic tags generated by the title prompt. */
  tags?: string[];
  /** Primary company/product mark inferred from the lead story. */
  brandLogo?: string;
  /** Cover layout template. */
  coverTemplate?: "left-hero" | "right-hero" | "bottom-banner" | "poster-panel";
  /** 日期标签 */
  dateLabel?: string;
}

const titleLength = (text: string): number => {
  return Array.from(text.replace(/\s+/g, "")).length;
};

const BRAND_MARKS: Record<
  string,
  {
    label: string;
    mark: string;
    bg: string;
    fg: string;
    markFg?: string;
  }
> = {
  Meta: { label: "Meta", mark: "∞", bg: "#0668E1", fg: "#ffffff" },
  Google: { label: "Google", mark: "G", bg: "#ffffff", fg: "#202124", markFg: "#4285F4" },
  Cloudflare: { label: "Cloudflare", mark: "☁", bg: "#F38020", fg: "#ffffff" },
  Steam: { label: "Steam", mark: "S", bg: "#171A21", fg: "#ffffff" },
  Ladybird: { label: "Ladybird", mark: "L", bg: "#E4453A", fg: "#ffffff" },
  NVIDIA: { label: "NVIDIA", mark: "N", bg: "#76B900", fg: "#0b0f08" },
  Anthropic: { label: "Anthropic", mark: "A", bg: "#D8C3A5", fg: "#201914" },
  Apple: { label: "Apple", mark: "A", bg: "#f5f5f7", fg: "#1d1d1f" },
};

const splitTitle = (title: string): { kicker: string; impact: string } => {
  const normalized = title.replace(/\s+/g, " ").trim();
  const commaMatch = normalized.match(/^(.{2,18})[，,：:](.+)$/);
  if (commaMatch) {
    return { kicker: commaMatch[1].trim(), impact: commaMatch[2].trim() };
  }
  const impactPatterns = [
    /(超?\d+[万亿]?[A-Za-z\u4e00-\u9fff]*被盗.*)$/,
    /(超?\d+[万亿]?[A-Za-z\u4e00-\u9fff]*被劫持.*)$/,
    /(超?\d+[万亿]?[A-Za-z\u4e00-\u9fff]*被接管.*)$/,
    /(中东玩家延迟飙升.*)$/,
    /(前端开源中立还剩几分.*)$/,
    /(16GB笔记本本地跑.*)$/,
  ];
  for (const pattern of impactPatterns) {
    const match = normalized.match(pattern);
    if (match?.index && match.index > 0) {
      return {
        kicker: normalized.slice(0, match.index).replace(/[，,：: ]+$/, ""),
        impact: match[1].trim(),
      };
    }
  }
  return { kicker: "", impact: normalized };
};

const splitImpactParts = (impact: string): { lead: string; rest: string } => {
  const match = impact.match(/^(超?\d+[万亿]?)(.*)$/);
  if (match) {
    return { lead: match[1], rest: match[2].trim() };
  }
  return { lead: "", rest: impact };
};

type CoverTemplate = NonNullable<CoverThumbnailProps["coverTemplate"]>;

const templateOverlay = (template: CoverTemplate): string => {
  if (template === "right-hero") {
    return `linear-gradient(
      to left,
      rgba(0,0,0,0.82) 0%,
      rgba(0,0,0,0.64) 38%,
      rgba(0,0,0,0.20) 70%,
      rgba(0,0,0,0.04) 100%
    ), linear-gradient(to bottom, rgba(0,0,0,0.03), rgba(0,0,0,0.58))`;
  }
  if (template === "bottom-banner") {
    return `linear-gradient(
      to bottom,
      rgba(0,0,0,0.06) 0%,
      rgba(0,0,0,0.10) 38%,
      rgba(0,0,0,0.78) 100%
    )`;
  }
  if (template === "poster-panel") {
    return `linear-gradient(
      to right,
      rgba(0,0,0,0.68) 0%,
      rgba(0,0,0,0.46) 48%,
      rgba(0,0,0,0.18) 100%
    ), linear-gradient(to bottom, rgba(0,0,0,0.08), rgba(0,0,0,0.62))`;
  }
  return `linear-gradient(
    to right,
    rgba(0,0,0,0.78) 0%,
    rgba(0,0,0,0.62) 38%,
    rgba(0,0,0,0.24) 68%,
    rgba(0,0,0,0.08) 100%
  ), linear-gradient(
    to bottom,
    rgba(0,0,0,0.04) 0%,
    rgba(0,0,0,0.15) 55%,
    rgba(0,0,0,0.65) 100%
  )`;
};

const textBoxStyle = (
  template: CoverTemplate,
  d: ReturnType<typeof useDesign>,
): React.CSSProperties => {
  const base: React.CSSProperties = {
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    gap: d.scaled(COVER_FS.contentGap),
  };
  if (template === "right-hero") {
    return {
      ...base,
      right: d.scaled(COVER_FS.contentRight),
      left: d.scaled(790),
      bottom: d.scaled(170),
      alignItems: "flex-start",
    };
  }
  if (template === "bottom-banner") {
    return {
      ...base,
      left: d.scaled(COVER_FS.contentLeft),
      right: d.scaled(COVER_FS.contentRight),
      bottom: d.scaled(74),
      alignItems: "flex-start",
    };
  }
  if (template === "poster-panel") {
    return {
      ...base,
      left: d.scaled(COVER_FS.contentLeft),
      top: d.scaled(205),
      width: d.scaled(1000),
      minHeight: d.scaled(660),
      padding: `${d.scaled(40)}px ${d.scaled(44)}px`,
      borderRadius: d.scaled(8),
      background: "rgba(0,0,0,0.42)",
      boxShadow: "0 26px 80px rgba(0,0,0,0.28)",
      justifyContent: "center",
    };
  }
  return {
    ...base,
    bottom: d.scaled(154),
    left: d.scaled(COVER_FS.contentLeft),
    right: d.scaled(650),
  };
};

const topBarStyle = (
  template: CoverTemplate,
  d: ReturnType<typeof useDesign>,
): React.CSSProperties => {
  const base: React.CSSProperties = {
    position: "absolute",
    top: d.scaled(54),
    left: d.scaled(COVER_FS.contentLeft),
    right: d.scaled(COVER_FS.contentRight),
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: d.scaled(24),
  };
  if (template === "right-hero") {
    return {
      ...base,
      flexDirection: "row-reverse",
    };
  }
  if (template === "bottom-banner") {
    return {
      ...base,
      top: d.scaled(56),
    };
  }
  if (template === "poster-panel") {
    return {
      ...base,
      left: d.scaled(COVER_FS.contentLeft),
      right: d.scaled(COVER_FS.contentRight),
    };
  }
  return base;
};

export const CoverThumbnail: React.FC<CoverThumbnailProps> = ({
  backgroundImage,
  title,
  subtitle: _subtitle,
  tags,
  brandLogo: _brandLogo,
  coverTemplate = "left-hero",
  dateLabel,
}) => {
  const d = useDesign();
  const topicTags = (tags ?? []).slice(0, 2);
  const { kicker, impact } = splitTitle(title);
  const { lead, rest } = splitImpactParts(impact);
  const compactTitle = titleLength(impact) > 16;
  const template = coverTemplate;
  const isBottomBanner = template === "bottom-banner";
  const isPosterPanel = template === "poster-panel";

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        position: "relative",
        overflow: "hidden",
        background: "#1a1a1a",
      }}
    >
      {/* 背景插画 */}
      <Img
        src={staticFile(backgroundImage)}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
        }}
      />

      {/* 渐变遮罩（底部加重，保证文字可读） */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          background: templateOverlay(template),
        }}
      />

      {/* 顶部识别条 */}
      <div style={topBarStyle(template, d)}>
        <div
          style={{
            marginLeft: "auto",
            display: "flex",
            alignItems: "center",
            gap: d.scaled(COVER_FS.brandGap),
            fontFamily: FONTS.mono,
            fontSize: d.scaled(COVER_FS.dateLabel),
            fontWeight: FW.heavy,
            color: "rgba(255,255,255,0.86)",
            letterSpacing: "0.03em",
            textShadow: "0 2px 12px rgba(0,0,0,0.55)",
          }}
        >
          <span>{BRAND_TEXT}</span>
          {dateLabel && <span style={{ opacity: 0.88 }}>{dateLabel}</span>}
        </div>
      </div>

      {/* 文字区域 */}
      <div style={textBoxStyle(template, d)}>
        {kicker && (
          <div
            style={{
              fontFamily: FONTS.sans,
              fontSize: d.scaled(COVER_FS.kicker),
              fontWeight: FW.heavy,
              color: "#ffffff",
              lineHeight: 1.1,
              textShadow: "0 2px 14px rgba(0,0,0,0.55)",
              maxWidth: isBottomBanner ? d.scaled(1280) : d.scaled(980),
            }}
          >
            {kicker}
          </div>
        )}

        {/* 主标题 — 支持 "\n" 显式换行 (2026-06-06 起, B 站长标题缩略图下不糊) */}
        <h1
          style={{
            fontFamily: FONTS.sans,
            fontSize: d.scaled(compactTitle ? COVER_FS.titleSmall : COVER_FS.title),
            fontWeight: FW.heavy,
            lineHeight: 1.03,
            color: "#ffffff",
            margin: 0,
            whiteSpace: "pre-line", // 保留 \n 自动换行；其他空白折叠
            textShadow: "0 2px 20px rgba(0,0,0,0.5), 0 1px 4px rgba(0,0,0,0.3)",
            maxWidth: isBottomBanner
              ? d.scaled(1480)
              : isPosterPanel
                ? d.scaled(850)
                : d.scaled(1120),
          }}
        >
          {lead ? (
            <>
              <span
                style={{
                  color: COLORS.brand,
                  fontSize: "inherit",
                  letterSpacing: "0",
                  WebkitTextStroke: `${d.scaled(2)}px rgba(255,255,255,0.12)`,
                }}
              >
                {lead}
              </span>
              {rest ? ` ${rest}` : ""}
            </>
          ) : (
            impact
          )}
        </h1>

        {topicTags.length > 0 && (
          <div
            style={{
              display: "flex",
              gap: d.scaled(COVER_FS.tagGap),
              flexWrap: "wrap",
              alignItems: "center",
            }}
          >
            {topicTags.map((tag) => (
              <span
                key={tag}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: d.scaled(10),
                  fontFamily: FONTS.sans,
                  fontSize: d.scaled(COVER_FS.tag),
                  fontWeight: FW.bold,
                  lineHeight: 1,
                  color: "#ffffff",
                  padding: `${d.scaled(10)}px ${d.scaled(18)}px`,
                  borderRadius: d.scaled(4),
                  background: "rgba(0,0,0,0.28)",
                  textShadow: "0 2px 10px rgba(0,0,0,0.55)",
                }}
              >
                <span
                  style={{
                    width: d.scaled(5),
                    height: d.scaled(28),
                    borderRadius: d.scaled(2),
                    background: COLORS.brand,
                    flex: "0 0 auto",
                  }}
                />
                {tag}
              </span>
            ))}
          </div>
        )}

        <div
          style={{
            width: d.scaled(520),
            height: d.scaled(7),
            borderRadius: d.scaled(4),
            background: `linear-gradient(90deg, ${COLORS.brand}, rgba(255,255,255,0))`,
            marginTop: d.scaled(8),
          }}
        />
      </div>
    </div>
  );
};
